const state={date:Utils.today(),day:null,activity:null,deferredInstall:null};
const childcare={dropoff:'등원',pickup:'하원',bath:'씻기',bedtime:'아기 재우기'};
const chores={dishesAm:'설거지 · 오전',dishesPm:'설거지 · 오후',vacuum:'청소기',laundry:'빨래',recycling:'분리수거',bathroom:'화장실 청소'};
const people=['나','남편','같이'];
document.addEventListener('DOMContentLoaded',init);
async function init(){await DB.open();bindNav();buildRows();bindInputs();setExportDates();document.querySelector('#statsMonth').value=Utils.today().slice(0,7);await loadToday();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;document.querySelector('#installBtn').hidden=false})}
function bindNav(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav-btn,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='recordsView')await renderRecords();if(b.dataset.view==='statsView')await renderStats();scrollTo(0,0)})}
function buildRows(){const row=(key,label,opts)=>`<div class="choice-row" style="--choices:${opts.length}"><span class="row-label">${label}</span>${opts.map(o=>`<button class="choice-btn" data-key="${key}" data-value="${o}">${o}</button>`).join('')}</div>`,make=(root,items,opts)=>root.innerHTML=Object.entries(items).map(([k,l])=>row(k,l,opts)).join('');make(document.querySelector('#childcareRows'),childcare,people);const opts=[...people,'안 함'],daily=['dishesAm','dishesPm','vacuum','laundry'],occasional=['recycling','bathroom'];document.querySelector('#choreRows').innerHTML=`<div class="group-label">매일</div>${daily.map(k=>row(k,chores[k],opts)).join('')}<div class="group-label occasional">필요할 때</div>${occasional.map(k=>row(k,chores[k],opts)).join('')}`}
function bindInputs(){document.querySelectorAll('.activity-btn').forEach(b=>b.onclick=()=>openActivity(b.dataset.activity));document.querySelector('#childcareRows').onclick=e=>e.target.matches('button')&&choose('childcare',e.target);document.querySelector('#choreRows').onclick=e=>e.target.matches('button')&&choose('chores',e.target);document.querySelector('#sleepTime').onchange=e=>saveField('sleepTime',e.target.value);document.querySelector('#sleepNow').onclick=()=>{document.querySelector('#sleepTime').value=Utils.nowTime();saveField('sleepTime',Utils.nowTime())};document.querySelector('#memo').oninput=Utils.debounce(async e=>{state.day.memo=e.target.value;await DB.saveDay(state.day);document.querySelector('#memoState').textContent='저장됨'});document.querySelector('#photoInput').onchange=e=>addFiles(e.target.files);document.querySelector('#audioInput').onchange=e=>addFiles(e.target.files);document.querySelector('#recordAudioBtn').onclick=toggleRecording;document.querySelector('[data-close-sheet]').onclick=closeSheet;document.querySelector('#sheetBackdrop').onclick=closeSheet;document.querySelector('#addEntryBtn').onclick=()=>addEntryRow();document.querySelector('#saveActivityBtn').onclick=saveActivity;document.querySelector('#recordDate').onchange=e=>renderRecordDetail(e.target.value);document.querySelector('#statsMonth').onchange=renderStats;document.querySelector('#statsCategoryTabs').onclick=e=>{if(!e.target.matches('button'))return;document.querySelectorAll('#statsCategoryTabs button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderStats()};document.querySelector('#pdfBtn').onclick=()=>PDFExport.run(document.querySelector('#exportStart').value,document.querySelector('#exportEnd').value);document.querySelector('#backupBtn').onclick=()=>Backup.download();document.querySelector('#restoreInput').onchange=async e=>{try{await Backup.restore(e.target.files[0]);await loadToday()}catch{Utils.toast('백업 파일을 확인해주세요.')}};document.querySelector('#settingsBtn').onclick=()=>document.querySelector('#settingsModal').hidden=false;document.querySelector('#settingsClose').onclick=()=>document.querySelector('#settingsModal').hidden=true;document.querySelector('#installBtn').onclick=()=>state.deferredInstall?.prompt();document.querySelector('#wakeLockToggle').onchange=async e=>{if(e.target.checked&&'wakeLock'in navigator)try{state.wakeLock=await navigator.wakeLock.request('screen')}catch{e.target.checked=false;Utils.toast('이 기기에서는 사용할 수 없습니다.')}}}
async function loadToday(){state.day=await DB.getDay(state.date);document.querySelector('#todayDate').textContent=Utils.formatDate(state.date);document.querySelector('#sleepTime').value=state.day.sleepTime||'';document.querySelector('#memo').value=state.day.memo||'';paintChoices();paintActivities();paintProgress();await renderAttachments()}
async function choose(group,btn){const key=btn.dataset.key,val=btn.dataset.value;state.day[group][key]=state.day[group][key]===val?'':val;await DB.saveDay(state.day);paintChoices();paintProgress();Utils.toast('저장했습니다.')}
async function saveField(key,value){state.day[key]=value;await DB.saveDay(state.day);paintProgress();Utils.toast('저장했습니다.')}
function paintChoices(){document.querySelectorAll('.choice-btn').forEach(b=>{const group=b.closest('#childcareRows')?'childcare':'chores';b.classList.toggle('selected',state.day[group]?.[b.dataset.key]===b.dataset.value)})}
function paintActivities(){document.querySelectorAll('.activity-btn').forEach(b=>{const n=state.day.activities?.[b.dataset.activity]?.length||0;b.classList.toggle('selected',n>0);b.querySelector('small').textContent=n?`${n}회 기록`:'기록하기'})}
function paintProgress(){const count=Object.values(state.day.childcare||{}).filter(Boolean).length+Object.values(state.day.chores||{}).filter(Boolean).length+(state.day.sleepTime?1:0)+(state.day.activities?.golf?.length?1:0)+(state.day.activities?.motorcycle?.length?1:0);document.querySelector('#todayProgress b').textContent=count}
function openActivity(type){state.activity=type;const labels={golf:'골프',motorcycle:'오토바이'};document.querySelector('#sheetTitle').textContent=labels[type];const entries=state.day.activities[type]||[];document.querySelector('#activityEntries').innerHTML='';(entries.length?entries:[{start:Utils.nowTime(),end:''}]).forEach(addEntryRow);document.querySelector('#sheetBackdrop').hidden=false;document.querySelector('#activitySheet').hidden=false}
function addEntryRow(v={start:'',end:''}){const row=document.createElement('div');row.className='entry-row';row.innerHTML=`<label>외출 시간<input class="start" type="time" value="${v.start||''}"><button class="now-link" type="button">지금</button></label><label>귀가 시간<input class="end" type="time" value="${v.end||''}"><button class="now-link" type="button">지금</button></label><button class="delete-btn" aria-label="시간 삭제">×</button>`;row.querySelectorAll('.now-link').forEach(b=>b.onclick=()=>b.previousElementSibling.value=Utils.nowTime());row.querySelector('.delete-btn').onclick=()=>row.remove();document.querySelector('#activityEntries').append(row)}
async function saveActivity(){const entries=[...document.querySelectorAll('.entry-row')].map(r=>({id:Utils.uid(),start:r.querySelector('.start').value,end:r.querySelector('.end').value})).filter(x=>x.start||x.end);state.day.activities[state.activity]=entries;await DB.saveDay(state.day);paintActivities();paintProgress();closeSheet();Utils.toast('외출 기록을 저장했습니다.')}
function closeSheet(){document.querySelector('#sheetBackdrop').hidden=true;document.querySelector('#activitySheet').hidden=true}
async function addFiles(list){for(const file of list)await DB.addFile({id:Utils.uid(),date:state.date,name:file.name,type:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),blob:file});await renderAttachments();Utils.toast(`${list.length}개 파일을 저장했습니다.`)}
async function renderAttachments(){const list=await DB.filesForDate(state.date),root=document.querySelector('#attachmentList');root.innerHTML='';for(const f of list){const el=document.createElement('div');el.className='attachment-item';let media=f.type.startsWith('image/')?`<img src="${URL.createObjectURL(f.blob)}" alt="">`:'<span>♪</span>';el.innerHTML=`${media}<div class="file-info"><div class="file-name">${Utils.escape(f.name)}</div><small>${Utils.bytes(f.size)}</small></div><button class="delete-btn">삭제</button>`;if(f.type.startsWith('audio/'))el.onclick=e=>{if(!e.target.matches('button'))new Audio(URL.createObjectURL(f.blob)).play()};el.querySelector('button').onclick=async()=>{if(confirm('이 첨부를 삭제할까요?')){await DB.deleteFile(f.id);renderAttachments()}};root.append(el)}}
async function toggleRecording(){const b=document.querySelector('#recordAudioBtn');try{if(!AudioRecorder.isRecording()){await AudioRecorder.start();b.textContent='녹음 끝내기';b.style.background='#102a43';b.style.color='#fff'}else{const blob=await AudioRecorder.stop();await DB.addFile({id:Utils.uid(),date:state.date,name:`녹음-${new Date().toTimeString().slice(0,8).replaceAll(':','')}.webm`,type:blob.type,size:blob.size,createdAt:new Date().toISOString(),blob});b.textContent='녹음';b.removeAttribute('style');await renderAttachments();Utils.toast('녹음을 저장했습니다.')}}catch{Utils.toast('마이크 권한을 허용해주세요.')}}
async function renderRecords(){const days=await DB.allDays(),root=document.querySelector('#recentRecords');if(!days.length){root.innerHTML='<div class="empty">아직 저장된 기록이 없습니다.</div>';return}document.querySelector('#recordDate').value=days[0].date;await renderRecordDetail(days[0].date);root.innerHTML='<h2 style="font-size:16px;margin-top:25px">최근 기록</h2>'+days.slice(0,30).map(d=>`<button class="record-card" style="width:100%;text-align:left" data-date="${d.date}"><h3>${Utils.formatDate(d.date)}</h3><span>${daySummary(d)}</span></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.querySelector('#recordDate').value=b.dataset.date;renderRecordDetail(b.dataset.date)})}
function daySummary(d){const s=[];if(d.activities?.golf?.length)s.push('골프');if(d.activities?.motorcycle?.length)s.push('오토바이');if(Object.values(d.childcare||{}).some(Boolean))s.push('육아');if(Object.values(d.chores||{}).some(Boolean))s.push('집안일');return s.join(' · ')||'메모/첨부 기록'}
async function renderRecordDetail(date){const d=await DB.getDay(date),files=await DB.filesForDate(date),lines=[];for(const [k,l] of Object.entries({golf:'골프',motorcycle:'오토바이'})){const a=d.activities?.[k]||[];if(a.length)lines.push([l,a.map(x=>`${x.start||'미입력'}~${x.end||'미입력'}`).join(', ')])}for(const [k,l] of Object.entries(childcare))if(d.childcare?.[k])lines.push([l,d.childcare[k]]);if(d.sleepTime)lines.push(['아이 잠든 시간',d.sleepTime]);for(const [k,l] of Object.entries(chores))if(d.chores?.[k])lines.push([l,d.chores[k]]);if(files.length)lines.push(['첨부',`${files.length}개`]);if(d.memo)lines.push(['메모',d.memo]);document.querySelector('#recordDetail').innerHTML=lines.length?`<div class="record-card"><h3>${Utils.formatDate(date)}</h3>${lines.map(x=>`<div class="record-line"><b>${x[0]}</b><span>${Utils.escape(x[1])}</span></div>`).join('')}</div>`:'<div class="empty">이 날짜에는 기록이 없습니다.</div>'}
async function renderStats(){const month=document.querySelector('#statsMonth').value||Utils.today().slice(0,7),start=month+'-01',last=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate(),end=month+'-'+String(last).padStart(2,'0'),days=await DB.getDays(start,end),cat=document.querySelector('#statsCategoryTabs .active')?.dataset.category||'childcare';const items=cat==='childcare'?childcare:cat==='chores'?chores:{golf:'골프',motorcycle:'오토바이'},counts={};for(const key of Object.keys(items)){counts[key]={나:0,남편:0,같이:0,total:0,dates:[]};for(const d of days){const value=cat==='outing'?(d.activities?.[key]?.length?true:false):d[cat]?.[key];if(value){counts[key].total++;counts[key].dates.push(d.date);if(value!==true&&counts[key][value]!==undefined)counts[key][value]++}}}const root=document.querySelector('#statsItems');root.innerHTML=Object.entries(items).map(([k,l])=>`<button class="stat-item" data-key="${k}"><span>${l}</span><b>${counts[k].total}<small>회</small></b></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{root.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');showStatDetail(items[b.dataset.key],counts[b.dataset.key],cat)});root.querySelector('button')?.click()}
function showStatDetail(label,c,cat){const max=Math.max(c.나,c.남편,c.같이,1);document.querySelector('#statsDetail').innerHTML=`<div class="detail-head"><div><small>선택 항목</small><h3>${label}</h3></div><strong>${c.total}<small>일</small></strong></div>${cat==='outing'?'<p class="stats-note">같은 날 여러 번 기록해도 월 통계에서는 1일로 계산합니다.</p>':`<div class="bar-row"><span>나</span><i><em style="width:${c.나/max*100}%"></em></i><b>${c.나}회</b></div><div class="bar-row"><span>남편</span><i><em style="width:${c.남편/max*100}%"></em></i><b>${c.남편}회</b></div><div class="bar-row"><span>같이</span><i><em style="width:${c.같이/max*100}%"></em></i><b>${c.같이}회</b></div>`}<div class="date-chips">${c.dates.map(d=>`<span>${Number(d.slice(8))}일</span>`).join('')||'<small>이번 달 기록이 없습니다.</small>'}</div>`}
function setExportDates(){const end=Utils.today(),d=new Date();d.setDate(d.getDate()-29);document.querySelector('#exportEnd').value=end;document.querySelector('#exportStart').value=d.toLocaleDateString('sv-SE')}
