const state={date:Utils.today(),day:null,activity:null,soloPerson:null,deferredInstall:null};
const startChips=[['time',Outing.START_MODES.time],['now','지금'],['unknown',Outing.START_MODES.unknown]];
const endChips=[['time',Outing.END_MODES.time],['now','지금'],['unknown',Outing.END_MODES.unknown],['out',Outing.END_MODES.out]];
document.addEventListener('DOMContentLoaded',init);
async function init(){await DB.open();bindNav();buildRows();bindInputs();bindMemoInputs();bindArchive();setExportDates();document.querySelector('#statsMonth').value=Utils.today().slice(0,7);document.querySelector('#archiveDate').value=Utils.today();await loadToday();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;document.querySelector('#installBtn').hidden=false})}
function bindNav(){document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav-btn').forEach(x=>{x.classList.remove('active');x.removeAttribute('aria-current')});document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');b.setAttribute('aria-current','page');document.querySelector('#'+b.dataset.view).classList.add('active');if(b.dataset.view==='recordsView')await renderRecords();if(b.dataset.view==='statsView')await renderStats();if(b.dataset.view==='filesView')await renderArchive();scrollTo(0,0)})}
function buildRows(){const row=(group,key,label)=>{const opts=Labels.optionsFor(group,key),wide=Labels.wideChoiceRows.includes(key)?' wide':'';return`<div class="choice-row${wide}" data-row-key="${key}" style="--choices:${opts.length}"><span class="row-label">${label}</span>${opts.map(o=>`<button class="choice-btn" data-key="${key}" data-value="${o}">${o}</button>`).join('')}</div>`};document.querySelector('#childcareRows').innerHTML=Object.entries(Labels.childcare).map(([k,l])=>row('childcare',k,l)).join('');document.querySelector('#choreRows').innerHTML=Labels.choreGroups.map((g,i)=>`<div class="group-label${i?' occasional':''}">${g.label}</div>`+g.keys.map(k=>row('chores',k,Labels.chores[k])).join('')).join('')}
function bindInputs(){document.querySelectorAll('.activity-btn:not(.solo-care-btn)').forEach(b=>b.onclick=()=>openActivity(b.dataset.activity));document.querySelectorAll('.solo-care-btn').forEach(b=>b.onclick=()=>openSoloCare(b.dataset.person));document.querySelector('#childcareRows').onclick=e=>e.target.matches('button')&&choose('childcare',e.target);document.querySelector('#choreRows').onclick=e=>e.target.matches('button')&&choose('chores',e.target);document.querySelector('#sleepTime').onchange=e=>saveField('sleepTime',e.target.value);document.querySelector('#sleepNow').onclick=()=>{document.querySelector('#sleepTime').value=Utils.nowTime();saveField('sleepTime',Utils.nowTime())};document.querySelector('#memo').oninput=Utils.debounce(async e=>{state.day.memo=e.target.value;state.day=await DB.saveDay(state.day);document.querySelector('#memoState').textContent='저장됨'});document.querySelector('#photoInput').onchange=e=>addFiles(e.target.files);document.querySelector('#audioInput').onchange=e=>addFiles(e.target.files);document.querySelector('#recordAudioBtn').onclick=toggleRecording;document.querySelector('[data-close-sheet]').onclick=closeSheet;document.querySelector('[data-close-solo]').onclick=closeSheet;document.querySelector('#sheetBackdrop').onclick=closeSheet;document.querySelector('#addEntryBtn').onclick=()=>addEntryRow();document.querySelector('#saveActivityBtn').onclick=saveActivity;document.querySelector('#addSoloCareBtn').onclick=()=>addSoloCareRow();document.querySelector('#saveSoloCareBtn').onclick=saveSoloCare;document.querySelector('#recordDate').onchange=e=>renderRecordDetail(e.target.value);document.querySelector('#statsMonth').onchange=renderStats;document.querySelector('#statsCategoryTabs').onclick=e=>{if(!e.target.matches('button'))return;document.querySelectorAll('#statsCategoryTabs button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderStats()};document.querySelector('#pdfBtn').onclick=()=>PDFExport.run(document.querySelector('#exportStart').value,document.querySelector('#exportEnd').value);document.querySelector('#backupBtn').onclick=()=>Backup.download();document.querySelector('#restoreInput').onchange=async e=>{try{await Backup.restore(e.target.files[0]);await loadToday()}catch{Utils.toast('백업 파일을 확인해주세요.')}};document.querySelector('#settingsBtn').onclick=()=>document.querySelector('#settingsModal').hidden=false;document.querySelector('#settingsClose').onclick=()=>document.querySelector('#settingsModal').hidden=true;document.querySelector('#installBtn').onclick=()=>state.deferredInstall?.prompt();document.querySelector('#wakeLockToggle').onchange=async e=>{if(e.target.checked&&'wakeLock'in navigator)try{state.wakeLock=await navigator.wakeLock.request('screen')}catch{e.target.checked=false;Utils.toast('이 기기에서는 사용할 수 없습니다.')}}}
function bindMemoInputs(){for(const [id,key]of[['daycarePrepMemo','daycarePrepMemo'],['choreMemo','choreMemo']])document.querySelector('#'+id).oninput=Utils.debounce(async e=>{state.day[key]=e.target.value;state.day=await DB.saveDay(state.day);document.querySelector('#'+id+'State').textContent='저장됨';paintProgress()})}
async function loadToday(){state.day=await DB.getDay(state.date);document.querySelector('#todayDate').textContent=Utils.formatDate(state.date);document.querySelector('#sleepTime').value=state.day.sleepTime||'';document.querySelector('#daycarePrepMemo').value=state.day.daycarePrepMemo||'';document.querySelector('#choreMemo').value=state.day.choreMemo||'';document.querySelector('#memo').value=state.day.memo||'';paintWeekendRows();paintChoices();paintActivities();paintSoloCare();paintProgress();await renderAttachments()}
/* 한국 시간 기준 토·일에는 오늘 화면에서 등원·하원 줄을 감춥니다.
   저장된 값은 건드리지 않으므로 기록·통계·PDF·백업에는 그대로 남습니다. */
function paintWeekendRows(){const weekend=Utils.isWeekendKST(state.date);Labels.weekdayOnlyChildcare.forEach(key=>{const row=document.querySelector(`#childcareRows .choice-row[data-row-key="${key}"]`);if(row)row.hidden=weekend})}
async function choose(group,btn){const key=btn.dataset.key,val=btn.dataset.value;state.day[group][key]=state.day[group][key]===val?'':val;state.day=await DB.saveDay(state.day);paintChoices();paintProgress();Utils.toast('저장했습니다.')}
async function saveField(key,value){state.day[key]=value;state.day=await DB.saveDay(state.day);paintProgress();Utils.toast('저장했습니다.')}
function paintChoices(){document.querySelectorAll('.choice-btn').forEach(b=>{const group=b.closest('#childcareRows')?'childcare':'chores';b.classList.toggle('selected',state.day[group]?.[b.dataset.key]===b.dataset.value)})}
function paintActivities(){document.querySelectorAll('.activity-btn:not(.solo-care-btn)').forEach(b=>{const entries=state.day.activities?.[b.dataset.activity]||[],n=entries.length;b.classList.toggle('selected',n>0);b.querySelector('small').textContent=n?(entries.some(e=>e.endMode==='out')?`${n}회 · 외출 중`:`${n}회 기록`):'기록하기'})}
function paintSoloCare(){document.querySelectorAll('.solo-care-btn').forEach(b=>{const n=(state.day.soloCare||[]).filter(e=>e.person===b.dataset.person).length;b.classList.toggle('selected',n>0);b.querySelector('small').textContent=n?`${n}회 기록`:'기록하기'})}
function paintProgress(){const count=Object.values(state.day.childcare||{}).filter(Boolean).length+Object.values(state.day.chores||{}).filter(Boolean).length+(state.day.sleepTime?1:0)+(state.day.daycarePrepMemo?1:0)+(state.day.choreMemo?1:0)+Object.keys(Labels.activities).filter(k=>state.day.activities?.[k]?.length).length+(state.day.soloCare?.length?1:0);document.querySelector('#todayProgress b').textContent=count}
function openActivity(type){state.activity=type;document.querySelector('#sheetTitle').textContent=Labels.activities[type];const entries=state.day.activities?.[type]||[];document.querySelector('#activityEntries').innerHTML='';(entries.length?entries:[{startMode:'time',start:Utils.nowTime(),endMode:'unknown'}]).forEach(e=>addEntryRow(e));document.querySelector('#sheetBackdrop').hidden=false;document.querySelector('#activitySheet').hidden=false}
function readEntryRow(row){return{id:row.dataset.id,startMode:row.dataset.startMode,start:row.querySelector('.start').value,endMode:row.dataset.endMode,end:row.querySelector('.end').value}}
function addEntryRow(entry){
  const e=Outing.normalize(entry||{startMode:'unknown',endMode:'unknown'}),row=document.createElement('div');
  row.className='entry-row';row.dataset.id=e.id;row.dataset.startMode=e.startMode;row.dataset.endMode=e.endMode;
  const chips=(field,list)=>`<div class="mode-chips" data-field="${field}">${list.map(([m,l])=>`<button type="button" data-mode="${m}">${l}</button>`).join('')}</div>`;
  row.innerHTML=`<div class="entry-field"><span class="entry-label">나간 시간</span>${chips('start',startChips)}<input class="start" type="time" value="${e.start}"></div>`
    +`<div class="entry-field"><span class="entry-label">들어온 시간</span>${chips('end',endChips)}<input class="end" type="time" value="${e.end}"></div>`
    +`<div class="entry-foot"><span class="entry-summary"></span><button class="delete-btn" type="button">이 기록 삭제</button></div>`;
  const paint=()=>{for(const field of['start','end']){const mode=row.dataset[field+'Mode'];row.querySelectorAll(`.mode-chips[data-field="${field}"] button`).forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));row.querySelector('.'+field).hidden=mode!=='time'}row.querySelector('.entry-summary').textContent=Outing.describe(readEntryRow(row))};
  row.querySelectorAll('.mode-chips').forEach(box=>box.onclick=ev=>{const btn=ev.target.closest('button');if(!btn)return;const field=box.dataset.field,input=row.querySelector('.'+field);if(btn.dataset.mode==='now'){row.dataset[field+'Mode']='time';input.value=Utils.nowTime()}else{row.dataset[field+'Mode']=btn.dataset.mode;if(btn.dataset.mode!=='time')input.value=''}paint()});
  row.querySelectorAll('input[type=time]').forEach(i=>i.oninput=paint);
  row.querySelector('.delete-btn').onclick=()=>row.remove();
  document.querySelector('#activityEntries').append(row);paint();
}
async function saveActivity(){const entries=[...document.querySelectorAll('#activityEntries .entry-row')].map(r=>Outing.normalize(readEntryRow(r)));state.day.activities[state.activity]=entries;state.day=await DB.saveDay(state.day);paintActivities();paintProgress();closeSheet();Utils.toast(entries.length?'외출 기록을 저장했습니다.':'외출 기록을 지웠습니다.')}
function openSoloCare(person){state.soloPerson=person;document.querySelector('#soloCareTitle').textContent=SoloCare.PEOPLE[person];const entries=(state.day.soloCare||[]).filter(e=>e.person===person);document.querySelector('#soloCareEntries').innerHTML='';(entries.length?entries:[{person,startMode:'time',start:Utils.nowTime(),endMode:'unknown'}]).forEach(addSoloCareRow);document.querySelector('#sheetBackdrop').hidden=false;document.querySelector('#soloCareSheet').hidden=false}
function readSoloCareRow(row){return{id:row.dataset.id,person:state.soloPerson,startMode:row.dataset.startMode,start:row.querySelector('.start').value,endMode:row.dataset.endMode,end:row.querySelector('.end').value}}
function addSoloCareRow(entry){const e=SoloCare.normalize(entry||{person:state.soloPerson,startMode:'unknown',endMode:'unknown'}),row=document.createElement('div');row.className='entry-row';row.dataset.id=e.id;row.dataset.startMode=e.startMode;row.dataset.endMode=e.endMode;const chips=(field,list)=>`<div class="mode-chips" data-field="${field}">${list.map(([m,l])=>`<button type="button" data-mode="${m}">${l}</button>`).join('')}</div>`,starts=[['time','직접 입력'],['now','지금'],['unknown','모름']],ends=[['time','직접 입력'],['now','지금'],['unknown','모름'],['ongoing','진행 중']];row.innerHTML=`<div class="entry-field"><span class="entry-label">시작 시간</span>${chips('start',starts)}<input class="start" type="time" value="${e.start}"></div><div class="entry-field"><span class="entry-label">종료 시간</span>${chips('end',ends)}<input class="end" type="time" value="${e.end}"></div><div class="entry-foot"><span class="entry-summary"></span><button class="delete-btn" type="button">이 기록 삭제</button></div>`;const paint=()=>{for(const field of['start','end']){const mode=row.dataset[field+'Mode'];row.querySelectorAll(`.mode-chips[data-field="${field}"] button`).forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));row.querySelector('.'+field).hidden=mode!=='time'}row.querySelector('.entry-summary').textContent=SoloCare.describe(readSoloCareRow(row)).replace(SoloCare.PEOPLE[state.soloPerson]+' · ','')};row.querySelectorAll('.mode-chips').forEach(box=>box.onclick=ev=>{const btn=ev.target.closest('button');if(!btn)return;const field=box.dataset.field,input=row.querySelector('.'+field);if(btn.dataset.mode==='now'){row.dataset[field+'Mode']='time';input.value=Utils.nowTime()}else{row.dataset[field+'Mode']=btn.dataset.mode;if(btn.dataset.mode!=='time')input.value=''}paint()});row.querySelectorAll('input[type=time]').forEach(i=>i.oninput=paint);row.querySelector('.delete-btn').onclick=()=>row.remove();document.querySelector('#soloCareEntries').append(row);paint()}
async function saveSoloCare(){const other=(state.day.soloCare||[]).filter(e=>e.person!==state.soloPerson),entries=[...document.querySelectorAll('#soloCareEntries .entry-row')].map(r=>SoloCare.normalize(readSoloCareRow(r)));state.day.soloCare=[...other,...entries];state.day=await DB.saveDay(state.day);paintSoloCare();paintProgress();closeSheet();Utils.toast(entries.length?'혼자 육아 기록을 저장했습니다.':'혼자 육아 기록을 지웠습니다.')}
function closeSheet(){document.querySelector('#sheetBackdrop').hidden=true;document.querySelector('#activitySheet').hidden=true;document.querySelector('#soloCareSheet').hidden=true}
async function addFiles(list){for(const file of list)await DB.addFile({id:Utils.uid(),date:state.date,name:file.name,type:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),blob:file});await renderAttachments();Utils.toast(`${list.length}개 파일을 저장했습니다.`)}
async function renderAttachments(){const list=await DB.filesForDate(state.date),root=document.querySelector('#attachmentList');root.innerHTML='';for(const f of list)root.append(makeFileItem(f,false))}
function makeFileItem(f,archive=false){const el=document.createElement('div');el.className='attachment-item'+(archive?' archive-item':'');const isImage=f.type.startsWith('image/'),isAudio=f.type.startsWith('audio/');let media=isImage?`<img src="${URL.createObjectURL(f.blob)}" alt="">`:`<span class="file-kind">${isAudio?'♪':'↧'}</span>`;el.innerHTML=`${media}<div class="file-info"><div class="file-name">${Utils.escape(f.name)}</div><small>${archive?`${Utils.escape(f.date)} · ${Utils.escape(f.category||'첨부')} · `:''}${Utils.bytes(f.size)}</small>${archive&&f.note?`<p>${Utils.escape(f.note)}</p>`:''}</div><div class="file-actions">${isImage?'<button class="file-view">보기</button>':''}${isAudio?'<button class="file-play">재생</button>':''}<button class="file-download">저장</button><button class="delete-btn">삭제</button></div>`;el.querySelector('.file-view')?.addEventListener('click',()=>openPreview(f));el.querySelector('.file-play')?.addEventListener('click',()=>{const audio=new Audio(URL.createObjectURL(f.blob));audio.play();audio.onended=()=>URL.revokeObjectURL(audio.src)});el.querySelector('.file-download').onclick=()=>downloadFile(f);el.querySelector('.delete-btn').onclick=async()=>{if(confirm('이 첨부를 삭제할까요?')){await DB.deleteFile(f.id);await renderAttachments();if(archive)await renderArchive()}};return el}
function downloadFile(f){Backup.saveBlob(f.blob,f.name);Utils.toast('원본 파일을 저장합니다.')}
function openPreview(f){if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl=URL.createObjectURL(f.blob);state.previewFile=f;document.querySelector('#previewImage').src=state.previewUrl;document.querySelector('#previewMeta').textContent=`${f.name} · ${f.date} · ${Utils.bytes(f.size)}`;document.querySelector('#previewModal').hidden=false}
function closePreview(){document.querySelector('#previewModal').hidden=true;document.querySelector('#previewImage').removeAttribute('src');if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl='';state.previewFile=null}
function bindArchive(){document.querySelector('#archiveInput').onchange=async e=>{const files=[...e.target.files],date=document.querySelector('#archiveDate').value||Utils.today(),category=document.querySelector('#archiveCategory').value,note=document.querySelector('#archiveNote').value.trim();for(const file of files)await DB.addFile({id:Utils.uid(),date,name:file.name,type:file.type||'application/octet-stream',size:file.size,category,note,createdAt:new Date().toISOString(),blob:file});e.target.value='';document.querySelector('#archiveNote').value='';await renderArchive();Utils.toast(`${files.length}개 자료를 보관했습니다.`)};document.querySelector('#previewClose').onclick=closePreview;document.querySelector('#previewModal').onclick=e=>{if(e.target.id==='previewModal')closePreview()};document.querySelector('#previewDownload').onclick=()=>state.previewFile&&downloadFile(state.previewFile)}
async function renderArchive(){const root=document.querySelector('#archiveList'),files=(await DB.allFiles()).sort((a,b)=>b.date.localeCompare(a.date)||(b.createdAt||'').localeCompare(a.createdAt||''));root.innerHTML=files.length?'':'<div class="empty">아직 보관한 자료가 없습니다.</div>';let last='';for(const f of files){if(f.date!==last){const h=document.createElement('h2');h.className='archive-date';h.textContent=Utils.formatDate(f.date);root.append(h);last=f.date}root.append(makeFileItem(f,true))}}
async function toggleRecording(){const b=document.querySelector('#recordAudioBtn');try{if(!AudioRecorder.isRecording()){await AudioRecorder.start();b.textContent='녹음 끝내기';b.style.background='#102a43';b.style.color='#fff'}else{const blob=await AudioRecorder.stop();await DB.addFile({id:Utils.uid(),date:state.date,name:`녹음-${new Date().toTimeString().slice(0,8).replaceAll(':','')}.webm`,type:blob.type,size:blob.size,createdAt:new Date().toISOString(),blob});b.textContent='녹음';b.removeAttribute('style');await renderAttachments();Utils.toast('녹음을 저장했습니다.')}}catch{Utils.toast('마이크 권한을 허용해주세요.')}}
async function renderRecords(){const days=await DB.allDays(),root=document.querySelector('#recentRecords');if(!days.length){root.innerHTML='<div class="empty">아직 저장된 기록이 없습니다.</div>';return}document.querySelector('#recordDate').value=days[0].date;await renderRecordDetail(days[0].date);root.innerHTML='<h2 style="font-size:16px;margin-top:25px">최근 기록</h2>'+days.slice(0,30).map(d=>`<button class="record-card" style="width:100%;text-align:left" data-date="${d.date}"><h3>${Utils.formatDate(d.date)}</h3><span>${daySummary(d)}</span></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.querySelector('#recordDate').value=b.dataset.date;renderRecordDetail(b.dataset.date)})}
function daySummary(d){const s=[];for(const [k,l] of Object.entries(Labels.activities))if(d.activities?.[k]?.length)s.push(l);if(Object.values(d.childcare||{}).some(Boolean)||d.daycarePrepMemo)s.push('육아');if(d.soloCare?.length)s.push(`혼자 육아 ${d.soloCare.length}회`);if(Object.values(d.chores||{}).some(Boolean)||d.choreMemo)s.push('집안일');return s.join(' · ')||'메모/첨부 기록'}
async function renderRecordDetail(date){const d=await DB.getDay(date),files=await DB.filesForDate(date),lines=[];for(const [k,l] of Object.entries(Labels.activities)){const a=d.activities?.[k]||[];if(a.length)lines.push([l,Outing.describeList(a).join('\n')])}if(d.soloCare?.length)lines.push(['혼자 육아',d.soloCare.map(SoloCare.describe).join('\n')]);for(const [k,l] of Object.entries(Labels.childcare))if(d.childcare?.[k])lines.push([l,d.childcare[k]]);if(d.daycarePrepMemo)lines.push(['등원 준비 내용',d.daycarePrepMemo]);if(d.sleepTime)lines.push(['아이 잠든 시간',d.sleepTime]);for(const [k,l] of Object.entries(Labels.chores))if(d.chores?.[k])lines.push([l,d.chores[k]]);if(d.choreMemo)lines.push(['청소·집안일 메모',d.choreMemo]);if(files.length)lines.push(['첨부',`${files.length}개`]);if(d.memo)lines.push(['메모',d.memo]);document.querySelector('#recordDetail').innerHTML=lines.length?`<div class="record-card"><h3>${Utils.formatDate(date)}</h3>${lines.map(x=>`<div class="record-line"><b>${x[0]}</b><span>${Utils.escape(x[1]).replace(/\n/g,'<br>')}</span></div>`).join('')}</div>`:'<div class="empty">이 날짜에는 기록이 없습니다.</div>'}
async function renderStats(){const month=document.querySelector('#statsMonth').value||Utils.today().slice(0,7),start=month+'-01',last=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate(),end=month+'-'+String(last).padStart(2,'0'),days=await DB.getDays(start,end),cat=document.querySelector('#statsCategoryTabs .active')?.dataset.category||'childcare';const items=cat==='childcare'?{...Labels.childcare,soloCare:'혼자 육아'}:cat==='chores'?Labels.chores:Labels.activities,unit=cat==='outing'?'일':'회',counts={};for(const key of Object.keys(items)){if(key==='soloCare'){counts[key]={total:days.reduce((n,d)=>n+(d.soloCare?.length||0),0),days};continue}const options=cat==='outing'?[]:Labels.statOptionsFor(cat,key),c={options,byOption:Object.fromEntries(options.map(o=>[o,0])),total:0,dates:[]};for(const d of days){const value=cat==='outing'?!!d.activities?.[key]?.length:d[cat]?.[key];if(value){c.total++;c.dates.push(d.date);if(value!==true&&c.byOption[value]!==undefined)c.byOption[value]++}}counts[key]=c}const root=document.querySelector('#statsItems');root.innerHTML=Object.entries(items).map(([k,l])=>`<button class="stat-item" data-key="${k}"><span>${l}</span><b>${counts[k].total}<small>${unit}</small></b></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{root.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');b.dataset.key==='soloCare'?showSoloCareStats(days):showStatDetail(items[b.dataset.key],counts[b.dataset.key],cat)});root.querySelector('button')?.click()}
function showSoloCareStats(days){const cards=Object.entries(SoloCare.PEOPLE).map(([person,label])=>{const s=SoloCare.summarize(days,person);return`<div class="solo-stat-card"><h4>${label.replace(' 혼자 육아','')}</h4><dl><div><dt>혼자 육아한 날짜 수</dt><dd>${s.days}일</dd></div><div><dt>총 기록 횟수</dt><dd>${s.count}회</dd></div><div><dt>확인되는 총시간</dt><dd>${SoloCare.formatMinutes(s.minutes)}</dd></div><div><dt>시간 미상 기록 수</dt><dd>${s.unknown}회</dd></div></dl></div>`}).join('');const root=document.querySelector('#statsDetail');root.classList.remove('wide-labels');root.innerHTML=`<div class="detail-head"><div><small>육아 통계</small><h3>혼자 육아</h3></div></div><div class="solo-stats">${cards}</div><p class="stats-note">같은 날 여러 번 기록해도 날짜 수는 1일, 횟수는 실제 기록 수로 계산합니다.</p>`}
function showStatDetail(label,c,cat){const options=c.options||[],max=Math.max(...options.map(o=>c.byOption[o]||0),1),longLabel=options.some(o=>o.length>3);const bars=options.map(o=>{const n=c.byOption[o]||0;return`<div class="bar-row"><span>${Utils.escape(o)}</span><i><em style="width:${n/max*100}%"></em></i><b>${n}회</b></div>`}).join('');const root=document.querySelector('#statsDetail');root.classList.toggle('wide-labels',cat!=='outing'&&longLabel);root.innerHTML=`<div class="detail-head"><div><small>선택 항목</small><h3>${label}</h3></div><strong>${c.total}<small>일</small></strong></div>${cat==='outing'?'<p class="stats-note">시간을 입력하지 않아도 그날 외출한 것으로 1일 계산합니다. 같은 날 여러 번 기록해도 1일입니다.</p>':bars}<div class="date-chips">${c.dates.map(d=>`<span>${Number(d.slice(8))}일</span>`).join('')||'<small>이번 달 기록이 없습니다.</small>'}</div>`}
function setExportDates(){const end=Utils.today(),d=new Date();d.setDate(d.getDate()-29);document.querySelector('#exportEnd').value=end;document.querySelector('#exportStart').value=d.toLocaleDateString('sv-SE')}
